### ISSUE TITLE
Show challenge completed message for users who have completed the frogtoberfest challenge

### ISSUE THREAD

**Issue by nishanbajracharya** [leapfrogtechnology/frogtoberfest#15]
**Current behavior:**
When a user completes the requirements for frogtoberfest, the profile page still says `Only # days left! You can do it!`.

**Expected behavior:**
After completing the requirements, the profile should show `Challenge Completed` or similar message. Something like `Thank you for your contributions! You have successfully completed Frogtoberfest 2019.`

If a user has `10/10` **PRs** and `4/4` **Other PRs** (_or more_), the profile page should show a challenge completed message instead of the days remaining message above the user name input field. This message should only be displayed if both the **PR** and **Other PR** have been completed. If either one is not completed, the profile should still show the days remaining message.

Screenshot from `Hacktoberfest` which shows how the profile looks for users who have completed the hacktoberfest challenge.

![image](https://user-images.githubusercontent.com/4490749/67289254-0a1c2d00-f4fe-11e9-84e4-d0b5cc7e3952.png)

Need not be so fancy, but an acknowledgement that the challenge is complete is needed.

**Steps to reproduce:**
- Complete the frogtoberfest challenge
- View user profile

**Image for reference:**
<img width="795" alt="Screen Shot 2019-10-22 at 14 06 37" src="https://user-images.githubusercontent.com/4490749/67268839-37a0b080-f4d5-11e9-9eb7-9238d015d2cf.png">

**Comment by codeanit** [comment]
Hi @nishanbajracharya/@kabirbaidhya 

 I was interested to raise a PR and tried to make the app run-able locally but the issue I have is while searching for my data with the username. Does this system search and fetch data when the 'check' button is hit?

The error sent is 'Couldn't find any data or we hit an error, try again?'

Or am I missing something?

Thank you.

![image](https://user-images.githubusercontent.com/414141/67279090-0aaac880-f4ea-11e9-935f-622f54fb4bb6.png)

**Comment by mesaugat** [comment]
@codeanit I think you missed the `export GITHUB_TOKEN=YOUR_TOKEN` step. You'll need to export your GitHub token so that the authorization to the GitHub API is possible. 

Follow the steps here: https://github.com/leapfrogtechnology/frogtoberfest#running-the-app

**Comment by kabirbaidhya** [comment]
Totally agree @nishanbajracharya. Thanks so much for coming with this proposal. I would mark this as a new feature request. 

Also, @nishanbajracharya could you please elaborate on or add few acceptance criteria under **Expected behavior** so that someone who'd be working on it (if not you) have a proper idea what he/she can do to work to do this feature :smile:.

**Comment by kabirbaidhya** [comment]
@nishanbajracharya You may want to review this PR - https://github.com/leapfrogtechnology/frogtoberfest/pull/19 which aims to resolve this.

**Comment by codeanit** [comment]
I did completely missed it @mesaugat. It works fine now. Thanks.
