### ISSUE TITLE
Setup unit tests and code coverage

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/frogtoberfest#18]
- Setup unit tests (use jest).
- Add test directory structure with few tests.
- Setup code coverage and add a code coverage badge.

**Comment by codeanit** [comment]
I'm taking the issue :) Thanks.

**Comment by kabirbaidhya** [comment]
Sure @codeanit. 

Please refer to this documentation for writing tests using jest - https://create-react-app.dev/docs/running-tests/. Since the codebase is bootstrapped with `create-react-app` it already has all the tooling setup for running tests based on jest. 

You'll need to:
 - add few initial tests - there are none right now
 - setup code-coverage / and run tests on CI.

**Comment by codeanit** [comment]
@kabirbaidhya, Thank you. 

I was looking at the doc :)
