### ISSUE TITLE
Fix design inconsistency

### ISSUE THREAD

**Issue by sagunji** [leapfrogtechnology/frogtoberfest#27]
**Current behavior:**
1. Text in the input field doesn't show completely
![image](https://user-images.githubusercontent.com/19725393/67615044-d3d4fb00-f7e6-11e9-9cf1-cde3f28f9db8.png)
2. Not enough space above the message `Only __ days left. You can do it.` in mobile view/responsive (width: 768px).
3. Clean up css in code level and remove unnecessary codes. 

**Expected behavior:**
1. The input field should show the whole text inserted.
2. Enough marginal space above the message on Responsive view and mobile view.

**Comment by kabirbaidhya** [comment]
@sagunji Can this be closed now?
