### ISSUE TITLE
Better date format on the pull request history

### ISSUE THREAD

**Issue by sagunji** [leapfrogtechnology/frogtoberfest#33]
**Current behaviour:**
The current date format of Pull Request created is:
![image](https://user-images.githubusercontent.com/19725393/67617344-ef99ca80-f801-11e9-8f9b-0d901f749365.png)

**Expected behaviour:**
Format the date as `October 26, 2019`

**Steps to reproduce:**
1. Insert a valid username on input field and click on `check` or `press Enter`.
2. Look at the history section.

**Comment by Vhndaree** [comment]
I think it will be more better if we can display something like `2 hrs ago`, `4 hrs ago` if PR created on same day and `October 26, 2019`, if PR was created on more than a day ago.

**Comment by kabirbaidhya** [comment]
@Vhndaree Agreed. It makes more sense and better from UX if we humanize the date like that.

**Comment by kabirbaidhya** [comment]
@sagunji @Vhndaree I've merged the issue that resolved the current requirement of this issue #33. 

Please do create a new issue for making the date relative as you suggested and someone (or perhaps you) can do a new PR :). 
> I think it will be more better if we can display something like 2 hrs ago, 4 hrs ago if PR is created on same day and October 26, 2019, if PR was created on more than a day ago.
