### ISSUE TITLE
Deployment preview and status check in the PR

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/frogtoberfest#37]
**Current behavior:**
Things get deployed automatically once merged into `master` - this is very good. But there's no CI check or progress (except for the travis which isn't responsible for deployment) visible on the PR. 

**Expected behavior:**
 - We need the deployment status and preview in the pull request. 
 - Use AWS Amplify + github actions (see #51)

**Steps to reproduce:**
 - Do a PR
 - Wait for it to get merged and then deployed. 
 - Go to https://frogtoberfest.lftechnology.com
 - You will know. 

cc @mesaugat

**Comment by sbimochan** [comment]
still issue?

**Comment by kabirbaidhya** [comment]
It still is. But we want to go with GitHub actions + AWS amplify instead of circle ci. Refer to this PR https://github.com/leapfrogtechnology/frogtoberfest/pull/51 to see what's remaining on this work.
