### ISSUE TITLE
Merge Status same for both merged and closed

### ISSUE THREAD

**Issue by sbimochan** [leapfrogtechnology/frogtoberfest#42]
**Current behavior:**
Even if the PR is closed, it is showing purple merged icon.

**Expected behavior:**
If the PR was closed, it should show red closed icon.

**Steps to reproduce:**
Enter my username i.e 'sbimochan'. My PR for homebrew was 'closed' but it is showing 'merged' icon.

**Comment by sbimochan** [comment]
@nishanbajracharya

**Comment by sbimochan** [comment]
Actually, github API is not providing merged status. It is only providing 'open' and 'closed' status. Hmm...

**Comment by kabirbaidhya** [comment]
Thanks for reporting @sbimochan. I'll mark this as a bug.

**Comment by Vhndaree** [comment]
github donot sent merge flag over same api we have to check **/repos/:owner/:repo/pulls/:pull_number/merge** api to check whether branch is merged or not, [Read mode]: https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged

**Comment by sbimochan** [comment]
@Vhndaree  https://hacktoberfestchecker.jenko.me/ have their backend but we are directly using Github API so it will be little trickier.

**Comment by kabirbaidhya** [comment]
@sbimochan You may want to review PR #45 which aims to resolve this.

**Comment by sbimochan** [comment]
Okay. I will.
