### ISSUE TITLE
Revamp overall design and UX part of frogtoberfest checker

### ISSUE THREAD

**Issue by ishan-is-me** [leapfrogtechnology/frogtoberfest#52]
Design I am thinking of is below:

![Frogtoberfest 2](https://user-images.githubusercontent.com/15309684/95316663-d7587980-08b3-11eb-9b3f-cf8eea6cdc1a.png)

![Frogtoberfest 3](https://user-images.githubusercontent.com/15309684/95316672-daec0080-08b3-11eb-9ce4-691788488551.png)

Please assign the issue to me. Thanks

**Comment by kabirbaidhya** [comment]
@ishan-me Sure. Design looks cool. Go for it.
