### ISSUE TITLE
Leaderboard route not working/not found

### ISSUE THREAD

**Issue by gaurab-khanal** [leapfrogtechnology/frogtoberfest#83]
Leaderboard route https://frogtoberfest-leaderboard.lftechnology.com/ is not found

**Comment by thenishantsapkota** [comment]
Hi @gaurab-khanal ,
The leaderboard was being fixed for bugs and some issues, and is back up again!

**Comment by thenishantsapkota** [comment]
Hi @gaurab-khanal , the leaderboard updates every day at 12:00 AM. The changes are not instantly refected!

**Comment by mesaugat** [comment]
@gaurab-khanal Leaderboard is up and running now as @thenishantsapkota mentioned. It is only updated in a daily basis.
