### ISSUE TITLE
Create new Page for Frogtoberfest Guidelines

### ISSUE THREAD

**Issue by RikLakhe** [leapfrogtechnology/frogtoberfest#94]
Context: Right now we are missing a guidelines page for Frogtoberfest.

Requirement:
1. A new page should be added to Frogtoberfest
2. Design as per current website design.
3. Add following content,

`Frogtoberfest Participation Guidelines
Frogtoberfest is dedicated to fostering high-quality contributions to Open Source projects.

Our mission is to inspire the Nepali community to get involved in Open Source and work together to improve projects that power our modern digital landscape.

With that in mind, we have prepared a few guidelines to ensure meaningful participation and contributions throughout Frogtoberfest.
Contribution guidelines
Meaningful code changes
Contributions should focus on meaningful code changes, such as bug fixes, new features, or improvements, rather than superficial alterations or cosmetic modifications.

Documentation enhancements
Encourage participants to contribute to project documentation, including updates, corrections, or clarifications, to improve the overall quality and usability of the project.

Issue tracking
Participants should prioritize issues or tasks listed in the project's issue tracker. This ensures alignment with project priorities and helps address existing challenges.

Value-added contributions
Stress the importance of making contributions that provide clear value to the open-source project and its users. Ask participants to consider how their contributions benefit the community.
Quality over quantity
The emphasis on quality has resulted in participants submitting fewer, but more substantial, PRs. This approach ensures that contributions are valuable to the open-source community.
Code review process 
The code review process will be conducted after the event's completion to maintain the quality of contributions.

Experienced reviewers will provide valuable feedback, enhancing the overall quality of PRs. The rejection of low-quality PRs will reinforce the importance of quality contributions, and participants will become more conscious of submitting meaningful changes.

This approach ensures that the final report for Frogtoberfest reflects the true value of contributions, as only high-quality PRs that meet the established guidelines will be counted towards participants' achievements.
Happy contributing!
As Frogtoberfest continues, we remain dedicated to these principles, ensuring that participants continue to make valuable contributions that benefit the open-source community. These guidelines will continue to serve as a cornerstone for promoting high-quality contributions and fostering a thriving open-source ecosystem.
`

**Comment by shresthalucky** [comment]
@RikLakhe Can you assign this to me? Thanks.

**Comment by RikLakhe** [comment]
DONE @shresthalucky

**Comment by shresthalucky** [comment]
@RikLakhe Please review the PR #95. Thanks.
